correct handling of javadoc and sources

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -37,20 +37,16 @@ jobs:
           echo "#dry" > dry.jar
           echo "#dry" > dry-sources.jar
           echo "#dry" > dry-javadoc.jar
-          mapfile -t out < <(DRY=echo main "${{ secrets.GITHUB_TOKEN }}" dry.jar "mygroup:myartifact:0.0:jar" "")
-          exp=(
-            "mvn -B -s settings.xml deploy:deploy-file -DgroupId=mygroup -DartifactId=myartifact -Dversion=0.0 -Dpackaging=jar -DrepositoryId=github -Dfile=dry.jar -DpomFile= -Durl=https://maven.pkg.github.com/ModelingValueGroup/upload-maven-package-action"
-          )
-          for i in 0 1 2; do
-            if [[ "${out[$i]:-}" == "${exp[$i]:-}" ]]; then
-              echo "... line $i: ok"
-            else
-              echo "::error::test failed"
-              echo "::error::    expected: ${exp[$i]:-}"
-              echo "::error::    output  : ${out[$i]:-}"
-              exit 44
-            fi
-          done
+
+          out="$(DRY=echo main "${{ secrets.GITHUB_TOKEN }}" dry.jar "mygroup:myartifact:0.0:jar" "")"
+          exp="mvn -B -s settings.xml deploy:deploy-file -DgroupId=mygroup -DartifactId=myartifact -Dversion=0.0 -Dpackaging=jar -DrepositoryId=github -Durl=https://maven.pkg.github.com/ModelingValueGroup/upload-maven-package-action -Dfile=dry.jar -Dsources=dry-sources.jar -Djavadoc=dry-javadoc.jar"
+
+          if [[ "$out" != "$exp" ]]; then
+            echo "::error::test failed"
+            echo "::error::    expected: $exp"
+            echo "::error::    output  : $out"
+            exit 44
+          fi
           rm dry.jar dry-sources.jar dry-javadoc.jar
           echo "all ok"
 
