also upload -'-sources' and '-javadoc'

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -32,20 +32,24 @@ jobs:
           set -euo pipefail
           . functions.sh  1>&2
           echo "#dry" > dry.pack
-          out="$(DRY=echo main \
-            "${{ secrets.GITHUB_TOKEN }}" \
-            "dry.pack" \
-            "mygroup:myartifact:0.0:pack" \
-            "")"
-          exp="mvn -B -s settings.xml deploy:deploy-file -DgroupId=mygroup -DartifactId=myartifact -Dversion=0.0 -Dpackaging=pack -DrepositoryId=github -Dfile=dry.pack -DpomFile= -Durl=https://maven.pkg.github.com/ModelingValueGroup/upload-maven-package-action"
-          if [[ "$out" != "$exp" ]]; then
-            echo "::error::test failed"
-            echo "::error::    expected: $exp"
-            echo "::error::    output  : $out"
-            exit 44
-          fi
+          mapfile out < <(DRY=echo main "${{ secrets.GITHUB_TOKEN }}" "dry.pack" "mygroup:myartifact:0.0:pack")
+          exp= (
+            "mvn -B -s settings.xml deploy:deploy-file -DgroupId=mygroup -DartifactId=myartifact -Dversion=0.0 -Dpackaging=pack -DrepositoryId=github -Dfile=dry.pack -DpomFile= -Durl=https://maven.pkg.github.com/ModelingValueGroup/upload-maven-package-action"
+            "mvn -B -s settings.xml deploy:deploy-file -DgroupId=mygroup -DartifactId=myartifact-sources -Dversion=0.0 -Dpackaging=pack -DrepositoryId=github -Dfile=dry-sources.pack -DpomFile= -Durl=https://maven.pkg.github.com/ModelingValueGroup/upload-maven-package-action"
+            "mvn -B -s settings.xml deploy:deploy-file -DgroupId=mygroup -DartifactId=myartifact-javadoc -Dversion=0.0 -Dpackaging=pack -DrepositoryId=github -Dfile=dry-javadoc.pack -DpomFile= -Durl=https://maven.pkg.github.com/ModelingValueGroup/upload-maven-package-action"
+          )
+          for i in 0 1 2; do
+            if [[ "${out[$i]}" == "${exp[$i]}" ]]; then
+              echo "... line $i: ok"
+            else
+              echo "::error::test failed"
+              echo "::error::    expected: ${exp[$i]}"
+              echo "::error::    output  : ${out[$i]}"
+              exit 44
+            fi
+          done
           rm dry.pack
-          echo "ok"
+          echo "all ok"
 
       - name: "push changes back to github"
         run:  |
